### ISSUE TITLE
null safe implementation

### ISSUE THREAD

**Issue by Dreamersoul** [danvick/form_builder_phone_field#4]
Will this library update to follow `flutter_form_builder ^6.0.0-nullsafety.1`?

**Comment by aneesh060** [comment]
Want to second Dreamersoul's comment. 6.0.0.nullsafety.1 is needed for null safety. Version 2.0 of this library is for null safety. There is no way to use this library in a null safe way if flutter_form_builder is not 6.0.0.

**Comment by Prn-Ice** [comment]
https://github.com/danvick/form_builder_phone_field/pull/6
